version: '3.4'
services:


  rasa-server1:
    image: rasa-bot:latest
    build: "./"
    restart: always
    volumes:
    - ./actions:/app/actions
    - ./data:/app/data
    - ./models:/app/models
    command: bash -c "rm -rf models/* && rasa train && rasa run --enable-api --cors \"*\" -p 8081"
    working_dir: "/app"
    ports:
    - '5005:8081'
    public: true
    networks:
    - all

  rasa-actions-server1:
    image: rasa-bot:latest
    build: "./"
    volumes:
    - ./actions:/app/actions
    command: bash -c "rasa", "run", "actions"
    working_dir: "/app"
    ports:
    - '5055:5055'
    public: true
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
